import type { Prisma } from '../../src/generated/prisma/client.js';

/**
 * Fase 11, stap 1: vaste startset recepten, 5 per recept-doel.
 * - LOSE_WEIGHT: lichter en eiwitrijk.
 * - BUILD_MUSCLE: eiwitrijk en calorierijker.
 * - GENERAL: algemeen gezond (Sterker worden, Conditie verbeteren, Fit worden).
 *
 * Regels (CLAUDE.md Fase 11): geen medische claims, kcal altijd als range.
 * De kcal-ranges zijn grove schattingen per portie op basis van gangbare
 * voedingswaarden, geen exacte berekening. Ingrediënten zijn voor één
 * portie. Upsert op `name`, dus de seed is herhaalbaar.
 */
export const RECIPES: Prisma.RecipeCreateInput[] = [
  // — Afvallen: lichter, eiwitrijk —
  {
    name: 'Griekse yoghurt met bessen en havermout',
    goal: 'LOSE_WEIGHT',
    mealType: 'BREAKFAST',
    description: 'Snel, fris ontbijt met veel eiwit en vezels.',
    ingredients: [
      '200 g magere Griekse yoghurt',
      '75 g blauwe bessen of frambozen',
      '3 el havermout (± 30 g)',
      'Snufje kaneel',
      '1 tl honing (optioneel)',
    ],
    steps: [
      'Schep de yoghurt in een kom.',
      'Strooi de havermout erover.',
      'Leg de bessen erop en bestrooi met kaneel.',
      'Druppel er eventueel wat honing over.',
    ],
    kcalMin: 280,
    kcalMax: 350,
  },
  {
    name: 'Groenteomelet met spinazie en champignons',
    goal: 'LOSE_WEIGHT',
    mealType: 'LUNCH',
    description: 'Vullende omelet met veel groente, klaar in tien minuten.',
    ingredients: [
      '3 eieren',
      '100 g champignons, in plakjes',
      'Handje verse spinazie',
      '1 tomaat, in blokjes',
      '1 tl olijfolie',
      'Peper en zout',
    ],
    steps: [
      'Klop de eieren los met peper en zout.',
      'Bak de champignons 3 minuten in de olie.',
      'Voeg de spinazie toe en laat slinken.',
      'Giet de eieren erover en bak op middelhoog vuur gaar.',
      'Strooi de tomaat erover en serveer.',
    ],
    kcalMin: 280,
    kcalMax: 360,
  },
  {
    name: 'Kip met geroosterde groenten uit de oven',
    goal: 'LOSE_WEIGHT',
    mealType: 'DINNER',
    description: 'Alles op één bakplaat: weinig afwas, veel groente.',
    ingredients: [
      '150 g kipfilet, in reepjes',
      '1 paprika, in stukken',
      '1 courgette, in halve maantjes',
      '1 rode ui, in parten',
      '1 el olijfolie',
      '1 tl paprikapoeder',
      'Peper en zout',
    ],
    steps: [
      'Verwarm de oven voor op 200 °C.',
      'Meng de groenten met de helft van de olie, peper en zout.',
      'Meng de kip met de rest van de olie en het paprikapoeder.',
      'Verdeel alles over een bakplaat met bakpapier.',
      'Rooster 20–25 minuten tot de kip gaar is.',
    ],
    kcalMin: 360,
    kcalMax: 440,
  },
  {
    name: 'Kabeljauw met broccoli en krieltjes',
    goal: 'LOSE_WEIGHT',
    mealType: 'DINNER',
    description: 'Lichte vismaaltijd met een frisse citroentoets.',
    ingredients: [
      '150 g kabeljauwfilet',
      '200 g broccoli, in roosjes',
      '150 g krieltjes',
      '1 tl olijfolie',
      '½ citroen',
      'Peper en zout',
    ],
    steps: [
      'Kook de krieltjes in 15 minuten gaar.',
      'Kook of stoom de broccoli de laatste 5 minuten mee.',
      'Bestrooi de vis met peper en zout en bak hem 3–4 minuten per kant in de olie.',
      'Serveer met een scheutje citroensap.',
    ],
    kcalMin: 330,
    kcalMax: 400,
  },
  {
    name: 'Hüttenkäse met komkommer en bieslook',
    goal: 'LOSE_WEIGHT',
    mealType: 'SNACK',
    description: 'Hartige, eiwitrijke tussendoor.',
    ingredients: ['150 g hüttenkäse', '½ komkommer, in blokjes', 'Bieslook, fijngeknipt', 'Peper'],
    steps: ['Meng de hüttenkäse met de komkommer.', 'Bestrooi met bieslook en peper.'],
    kcalMin: 140,
    kcalMax: 190,
  },

  // — Spieropbouw: eiwitrijk, calorierijker —
  {
    name: 'Overnight oats met kwark en pindakaas',
    goal: 'BUILD_MUSCLE',
    mealType: 'BREAKFAST',
    description: 'De avond ervoor klaarzetten, ’s ochtends meteen eten.',
    ingredients: [
      '70 g havermout',
      '150 g magere kwark',
      '150 ml halfvolle melk',
      '1 el pindakaas',
      '1 banaan',
    ],
    steps: [
      'Meng havermout, kwark en melk in een pot of bakje.',
      'Zet afgedekt een nacht in de koelkast.',
      'Snijd ’s ochtends de banaan in plakjes en leg die erop.',
      'Schep de pindakaas erover.',
    ],
    kcalMin: 560,
    kcalMax: 660,
  },
  {
    name: 'Volkoren wraps met kip en avocado',
    goal: 'BUILD_MUSCLE',
    mealType: 'LUNCH',
    description: 'Stevige lunch die je makkelijk meeneemt.',
    ingredients: [
      '2 volkoren wraps',
      '125 g kipfilet, in reepjes',
      '½ avocado',
      'Handje sla',
      '1 tomaat, in plakjes',
      'Peper en zout',
    ],
    steps: [
      'Bak de kip met peper en zout in een droge koekenpan gaar.',
      'Prak de avocado en smeer die over de wraps.',
      'Beleg met sla, tomaat en kip.',
      'Rol de wraps strak op.',
    ],
    kcalMin: 570,
    kcalMax: 680,
  },
  {
    name: 'Volkorenpasta met gehakt en tomatensaus',
    goal: 'BUILD_MUSCLE',
    mealType: 'DINNER',
    description: 'Klassieker met extra eiwit uit mager gehakt.',
    ingredients: [
      '100 g volkorenpasta (droog)',
      '150 g mager rundergehakt',
      '½ ui, gesnipperd',
      '1 teentje knoflook',
      '200 g tomatenblokjes',
      '1 tl Italiaanse kruiden',
      '20 g geraspte kaas',
    ],
    steps: [
      'Kook de pasta volgens de verpakking.',
      'Bak het gehakt rul met de ui en knoflook.',
      'Voeg de tomatenblokjes en kruiden toe en laat 10 minuten pruttelen.',
      'Meng met de pasta en strooi de kaas erover.',
    ],
    kcalMin: 720,
    kcalMax: 850,
  },
  {
    name: 'Zalm met rijst en sperziebonen',
    goal: 'BUILD_MUSCLE',
    mealType: 'DINNER',
    description: 'Voedzaam bord met vette vis, rijst en groente.',
    ingredients: [
      '150 g zalmfilet',
      '80 g rijst (droog)',
      '200 g sperziebonen',
      '1 tl olijfolie',
      '½ citroen',
      'Peper en zout',
    ],
    steps: [
      'Kook de rijst volgens de verpakking.',
      'Kook de sperziebonen in 8 minuten beetgaar.',
      'Bak de zalm 3–4 minuten per kant in de olie.',
      'Breng op smaak met citroen, peper en zout.',
    ],
    kcalMin: 640,
    kcalMax: 760,
  },
  {
    name: 'Kwark met banaan en walnoten',
    goal: 'BUILD_MUSCLE',
    mealType: 'SNACK',
    description: 'Royale eiwitrijke tussendoor, ook fijn na de training.',
    ingredients: ['250 g magere kwark', '1 banaan, in plakjes', '20 g walnoten'],
    steps: ['Schep de kwark in een kom.', 'Leg de banaan erop en strooi de walnoten erover.'],
    kcalMin: 340,
    kcalMax: 420,
  },

  // — Algemeen gezond: Sterker worden, Conditie verbeteren, Fit worden —
  {
    name: 'Volkorenboterham met ei en tomaat',
    goal: 'GENERAL',
    mealType: 'BREAKFAST',
    description: 'Eenvoudig ontbijt dat lang verzadigt.',
    ingredients: ['2 sneetjes volkorenbrood', '2 eieren', '1 tomaat, in plakjes', 'Peper en zout'],
    steps: [
      'Kook de eieren in 8 minuten hard, of bak ze in een droge pan.',
      'Beleg het brood met tomaat.',
      'Leg het ei erop en breng op smaak met peper en zout.',
    ],
    kcalMin: 330,
    kcalMax: 400,
  },
  {
    name: 'Couscoussalade met feta en groenten',
    goal: 'GENERAL',
    mealType: 'LUNCH',
    description: 'Frisse salade die ook koud goed smaakt.',
    ingredients: [
      '70 g couscous',
      '50 g feta, verkruimeld',
      '½ komkommer, in blokjes',
      '1 paprika, in blokjes',
      'Handje peterselie of munt',
      '1 el olijfolie',
      'Sap van ½ citroen',
    ],
    steps: [
      'Overgiet de couscous met kokend water en laat 5 minuten wellen.',
      'Maak los met een vork en laat iets afkoelen.',
      'Meng met de groenten, feta en kruiden.',
      'Maak aan met olie en citroensap.',
    ],
    kcalMin: 500,
    kcalMax: 580,
  },
  {
    name: 'Wokschotel met kip, groenten en noedels',
    goal: 'GENERAL',
    mealType: 'DINNER',
    description: 'Snelle wok voor een drukke avond.',
    ingredients: [
      '125 g kipfilet, in reepjes',
      '75 g noedels (droog)',
      '300 g wokgroenten',
      '1 teentje knoflook',
      '1 el sojasaus',
      '1 tl olie',
    ],
    steps: [
      'Kook de noedels volgens de verpakking.',
      'Roerbak de kip met de knoflook in de olie gaar.',
      'Voeg de wokgroenten toe en roerbak 4 minuten.',
      'Schep de noedels en sojasaus erdoor.',
    ],
    kcalMin: 540,
    kcalMax: 630,
  },
  {
    name: 'Linzencurry met rijst',
    goal: 'GENERAL',
    mealType: 'DINNER',
    description: 'Vegetarische curry, mild gekruid.',
    ingredients: [
      '60 g rode linzen',
      '60 g rijst (droog)',
      '½ ui, gesnipperd',
      '200 g tomatenblokjes',
      '100 ml lichte kokosmelk',
      '1 tl kerriepoeder',
      'Handje spinazie',
    ],
    steps: [
      'Kook de rijst volgens de verpakking.',
      'Fruit de ui met het kerriepoeder in een pan.',
      'Voeg linzen, tomaten, kokosmelk en 150 ml water toe.',
      'Laat 15 minuten zacht koken tot de linzen gaar zijn.',
      'Roer de spinazie erdoor en serveer met de rijst.',
    ],
    kcalMin: 520,
    kcalMax: 620,
  },
  {
    name: 'Appel met pindakaas',
    goal: 'GENERAL',
    mealType: 'SNACK',
    description: 'Simpele tussendoor met wat vezels en vet.',
    ingredients: ['1 appel', '1 el pindakaas (± 15 g)'],
    steps: ['Snijd de appel in partjes.', 'Dip de partjes in de pindakaas.'],
    kcalMin: 160,
    kcalMax: 220,
  },
];
